r – Read-only mode. This mode allows you to read from the file, but you can't make any changes to it. ...
w – Write-only mode. ...
a – Append-only mode. ...
r+ – Read + Write mode. ...
w+ – Write + Read mode. ...
a+ – Append + Read mode.
